<p style="text-align:center">
    <a href="https://github.com/binatnadata/event2-python-ERME_CLUB/tree/main" target="_blank">
    <img src="https://raw.githubusercontent.com/binatnadata/event2-python-ERME_CLUB/main/assets/banner_head.jpeg" width="800" height="500" alt="Collaboration banner"  />
    </a>
</p>

## Python labs -By Binatna Data-
- **Sessions of December 2023**
- **Session of 16/12/2023**

<hr>
<hr>

<p style="text-align:center">
    <a href="https://github.com/binatnadata/event2-python-ERME_CLUB/tree/main" target="_blank">
    <img src="https://raw.githubusercontent.com/binatnadata/event2-python-ERME_CLUB/main/assets/1_vPezx00A1u0WAfS8e8wBXQ.webp" width="400" height="500" alt="Numpy logo"  />
    </a>
</p>

1. Create a NumPy array `(arr1)` with values `[1, 2, 3, 4, 5]`.
2. Create a NumPy array `(arr2)` with values `[10, 20, 30, 40, 50]`.
3. Perform element-wise `multiplication` of `arr1` and `arr2`. Save the result in a new array `result_mult`.
4. Create a 3x3 identity matrix `identity_matrix`.
5. Check the `shape`, `size`, and `data type` of `arr1`.
6. `Reshape` `arr2` into a `5x1` matrix and name it `reshaped_arr2`.
7. Append a new element `6` to the end of `arr1` and name the new array `arr1_appended`.
8. Insert a new element `25` at index `2` in `arr2` and name the new array `arr2_inserted`.
9. Delete the element at index `3` in `arr1` and name the new array `arr1_deleted`.
10. Delete the first row in identity_matrix and name the new array `identity_matrix_deleted`.
11. Slice `arr1` to get elements `greater than 2` and name the result `arr1_slice_condition`.
12. Slice `arr2` to get elements `between index 1 and 3` (inclusive) and name the `result arr2_slice_interval`.
13. Concatenate `arr1` and `arr2` along a new axis and name the result `concatenated_arrays`.
14. Generate an array `random_array` of `10` random integers `between 0 and 100`.
15. Sample `3` random elements from `random_array` without `replacement`.
16. Save `random_array` to a `CSV file` named `"random_data.csv"`.

In [1]:
import numpy as np

# 1
arr1 = np.array([1, 2, 3, 4, 5])
print("Array 1 : ", arr1)

# 2
arr2 = np.array([10, 20, 30, 40, 50])
print("Array 2 : ", arr2)

# 3
result_mult = arr1 * arr2
print("The multiplication of arr1 and arr2: ", result_mult)


# 4
identity_matrix = np.eye(3)
print("identity_matrix : \n", identity_matrix) 

#5
print("Shape of arr1: ", arr1.shape)
print("Size of arr1: ", arr1.size)
print("Data type of arr1: ", arr1.dtype)

# 6
reshaped_arr2 = arr2.reshape((5, 1))
print("reshaped_arr2 (5,1): \n", reshaped_arr2)

# 7
arr1_appended = np.append(arr1, 6)
print("arr1_appended 6: ", arr1_appended)

# 8
arr2_inserted = np.insert(arr2, 2, 25)
print("arr2_inserted (25 at index 2): ", arr2_inserted)

# 9
arr1_deleted = np.delete(arr1, 3)
print("arr1_deleted (at index 3): ", arr1_deleted)

# 10
identity_matrix_deleted = np.delete(identity_matrix, 0, axis=0)
print("identity_matrix_deleted (delete first row): \n", identity_matrix_deleted)

# 11
arr1_slice_condition = arr1[arr1 > 2]
print("arr1_slice_condition (elements greater than 2): ", arr1_slice_condition)

# 12
arr2_slice_interval = arr2[1:4]
print("arr2_slice_interval (elements between index 1 and 3 (inclusive)): ", arr2_slice_interval)

# 13
concatenated_arrays = np.concatenate((arr1, arr2), axis=None)
print("concatenated_arrays (Concatenate arr1 and arr2): ", concatenated_arrays)

# 14
random_array = np.random.randint(0, 101, size=10)
print("random_array (random_array of 10 random): ", random_array)

# 15
random_samples = np.random.choice(random_array, size=3, replace=False)
print("random_samples (3 random elements): ", random_samples)

# 16
np.savetxt('random_data.csv', random_array, delimiter=',')
print("random_data.csv saved successfully.")

# 17
loaded_array = np.loadtxt('random_data.csv', delimiter=',')

# 18
loaded_array_sum = np.sum(loaded_array)
loaded_array_cumsum = np.cumsum(loaded_array)
loaded_array_mean = np.mean(loaded_array)

# 19
column_means_identity = np.mean(identity_matrix_deleted, axis=0)
print("column_means_identity: \n",column_means_identity)

# 20
results=np.array([loaded_array_sum, loaded_array_mean])
print("results : ", results)
np.savetxt('results.csv', results)
print("results.csv saved successfully.")

Array 1 :  [1 2 3 4 5]
Array 2 :  [10 20 30 40 50]
The multiplication of arr1 and arr2:  [ 10  40  90 160 250]
identity_matrix : 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Shape of arr1:  (5,)
Size of arr1:  5
Data type of arr1:  int32
reshaped_arr2 (5,1): 
 [[10]
 [20]
 [30]
 [40]
 [50]]
arr1_appended 6:  [1 2 3 4 5 6]
arr2_inserted (25 at index 2):  [10 20 25 30 40 50]
arr1_deleted (at index 3):  [1 2 3 5]
identity_matrix_deleted (delete first row): 
 [[0. 1. 0.]
 [0. 0. 1.]]
arr1_slice_condition (elements greater than 2):  [3 4 5]
arr2_slice_interval (elements between index 1 and 3 (inclusive)):  [20 30 40]
concatenated_arrays (Concatenate arr1 and arr2):  [ 1  2  3  4  5 10 20 30 40 50]
random_array (random_array of 10 random):  [58 38 57 53 33 61 86  3 62 93]
random_samples (3 random elements):  [ 3 33 58]
random_data.csv saved successfully.
column_means_identity: 
 [0.  0.5 0.5]
results :  [544.   54.4]
results.csv saved successfully.


# Exercise 2: Solar Energy Calculation

<p style="text-align:center">
    <img src="https://th.bing.com/th/id/R.b3c79851427a8a55723fe3827b31abec?rik=hhIrP8ict8gxIw&riu=http%3a%2f%2fnews.delaware.gov%2ffiles%2f2012%2f03%2fMotech-Solar-Panel-floating.jpg&ehk=Q3uAu91jOrnoGRCY6%2bd9acDMq6CEzBIKGJLdw9zD5B0%3d&risl=&pid=ImgRaw&r=0" width="500" height="200" alt="Solar Energy"  />
</p>

$$
E = A \times \eta \times I \times t
$$


1. Develop a script that utilizes the `pandas` library to read the contents of the csv file named `"solar_energy_data_by_binatnaData.csv"` into a DataFrame, and assign it the variable name `df`.
2. Display the first and last few rows of the DataFrame using the `head()` and `tail()` functions, and the column names. 
3. Rename the columns by the following names : `A, E, I, T`
4. Determine and print the `count of missing (NaN) values` for each column in the DataFrame.
5. Eliminate the `rows containing NaN values` from the DataFrame.
6. Check for `duplicate rows` in the DataFrame using the `duplicated()` method.
7. Calculate the Energy for each row by applying the formula: `Energy = Solar Panel Area * Solar Panel Efficiency * Solar Irradiance * Time`.
8. Calculate the energy for each row by applying the same `formula`, this time using a `function` that takes 4 `arguments`: A (Area), E (Efficiency), I (Irradiance), T (Time), then the function returns the calculated Energy. 
9. Introduce a new column in the DataFrame, naming it `"Energy"` and populate it with the calculated energy values.
9. Save the modified DataFrame with the additional `Energy` column to a `new csv file`.