<p style="text-align:center">
    <a href="https://github.com/binatnadata/event2-python-ERME_CLUB/tree/main" target="_blank">
    <img src="https://raw.githubusercontent.com/binatnadata/event2-python-ERME_CLUB/main/assets/banner_head.jpeg" width="800" height="500" alt="Collaboration banner"  />
    </a>
</p>

## Python labs -By Binatna Data-
- **Sessions of December 2023**
- **Session of 16/12/2023**

<hr>
<hr>

<p style="text-align:center">
    <a href="https://github.com/binatnadata/event2-python-ERME_CLUB/tree/main" target="_blank">
    <img src="https://raw.githubusercontent.com/binatnadata/event2-python-ERME_CLUB/main/assets/1_vPezx00A1u0WAfS8e8wBXQ.webp" width="400" height="500" alt="Numpy logo"  />
    </a>
</p>

1. Create a NumPy array `(arr1)` with values `[1, 2, 3, 4, 5]`.
2. Create a NumPy array `(arr2)` with values `[10, 20, 30, 40, 50]`.
3. Perform element-wise `multiplication` of `arr1` and `arr2`. Save the result in a new array `result_mult`.
4. Create a 3x3 identity matrix `identity_matrix`.
5. Check the `shape`, `size`, and `data type` of `arr1`.
6. `Reshape` `arr2` into a `5x1` matrix and name it `reshaped_arr2`.
7. Append a new element `6` to the end of `arr1` and name the new array `arr1_appended`.
8. Insert a new element `25` at index `2` in `arr2` and name the new array `arr2_inserted`.
9. Delete the element at index `3` in `arr1` and name the new array `arr1_deleted`.
10. Delete the first row in identity_matrix and name the new array `identity_matrix_deleted`.
11. Slice `arr1` to get elements `greater than 2` and name the result `arr1_slice_condition`.
12. Slice `arr2` to get elements `between index 1 and 3` (inclusive) and name the `result arr2_slice_interval`.
13. Concatenate `arr1` and `arr2` along a new axis and name the result `concatenated_arrays`.
14. Generate an array `random_array` of `10` random integers `between 0 and 100`.
15. Sample `3` random elements from `random_array` without `replacement`.
16. Save `random_array` to a `CSV file` named `"random_data.csv"`.

In [1]:
# import numpy package
import numpy as np

In [4]:
# 1
arr1 = np.array([1, 2, 3, 4, 5])
print("Array 1 : ", arr1)

Array 1 :  [1 2 3 4 5]


In [5]:
# verify the type
type(arr1)

numpy.ndarray

In [6]:
# 2
arr2 = np.array([10, 20, 30, 40, 50])
print("Array 2 : ", arr2)

Array 2 :  [10 20 30 40 50]


In [7]:
# 3
result_mult = arr1 * arr2
print("The multiplication of arr1 and arr2: ", result_mult)

The multiplication of arr1 and arr2:  [ 10  40  90 160 250]


In [10]:
# 4
identity_matrix = np.eye(3)
print("identity_matrix : \n", identity_matrix) 

identity_matrix : 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [72]:
arr1

array([1, 2, 3, 4, 5])

In [11]:
#5
print("Shape of arr1: ", arr1.shape)
print("Size of arr1: ", arr1.size)
print("Data type of arr1: ", arr1.dtype)

Shape of arr1:  (5,)
Size of arr1:  5
Data type of arr1:  int32


In [73]:
arr2

array([10, 20, 30, 40, 50])

In [14]:
# 6
reshaped_arr2 = arr2.reshape((5, 1))
print("reshaped_arr2 (5,1): \n", reshaped_arr2)

reshaped_arr2 (5,1): 
 [[10]
 [20]
 [30]
 [40]
 [50]]


In [74]:
arr1

array([1, 2, 3, 4, 5])

In [16]:
# 7
arr1_appended = np.append(arr1, 6)
print("arr1_appended 6: ", arr1_appended)

arr1_appended 6:  [1 2 3 4 5 6]


In [16]:
# 8
print("arr2 ------- ",arr2)
arr2_inserted = np.insert(arr2, 2, 25)
print("arr2_inserted (25 at index 2): ", arr2_inserted)

arr2 -------  [10 20 30 40 50]
arr2_inserted (25 at index 2):  [10 20 25 30 40 50]


In [75]:
arr1

array([1, 2, 3, 4, 5])

In [19]:
# 9
print('arr1 -------------', arr1 )
arr1_deleted = np.delete(arr1, 3)
print("arr1_deleted (at index 3): ", arr1_deleted)

arr1 ------------- [1 2 3 4 5]
arr1_deleted (at index 3):  [1 2 3 5]


In [21]:
# 10
print('identity matrix -----------')
print(identity_matrix)
identity_matrix_deleted = np.delete(identity_matrix, 0, axis=0)
print("identity_matrix_deleted (delete first row): \n", identity_matrix_deleted)

identity matrix -----------
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
identity_matrix_deleted (delete first row): 
 [[0. 1. 0.]
 [0. 0. 1.]]


In [76]:
arr1

array([1, 2, 3, 4, 5])

In [77]:
arr1 > 2

array([False, False,  True,  True,  True])

In [22]:
# 11
print('arr1 -------------', arr1)
arr1_slice_condition = arr1[arr1 > 2]
print("arr1_slice_condition (elements greater than 2): ", arr1_slice_condition)

arr1 ------------- [1 2 3 4 5]
arr1_slice_condition (elements greater than 2):  [3 4 5]


In [26]:
# 12
print('arr2 ---------- ', arr2)
arr2_slice_interval = arr2[1:4]
print("arr2_slice_interval (elements between index 1 and 3 (inclusive)): ", arr2_slice_interval)

arr2 ----------  [10 20 30 40 50]
arr2_slice_interval (elements between index 1 and 3 (inclusive)):  [20 30 40]


In [78]:
print(arr1)
print(arr2)

[1 2 3 4 5]
[10 20 30 40 50]


In [30]:
# 13
concatenated_arrays = np.concatenate((arr1, arr2), axis=None)
print("concatenated_arrays (Concatenate arr1 and arr2): ", concatenated_arrays)

concatenated_arrays (Concatenate arr1 and arr2):  [ 1  2  3  4  5 10 20 30 40 50]


In [92]:
# 14
random_array = np.random.randint(0, 101, size=10)
print("random_array (random_array of 10 random): ", random_array)

random_array (random_array of 10 random):  [100  70   2  76  69   2  78  20  14 100]


In [93]:
# 15
random_samples = np.random.choice(random_array, size=3, replace=False)
print("random_samples (3 random elements): ", random_samples)

random_samples (3 random elements):  [69 76  2]


In [63]:
random_array

array([75, 86, 95, 63, 14, 35, 79,  7, 88, 81])

In [94]:
random_array

array([100,  70,   2,  76,  69,   2,  78,  20,  14, 100])

In [95]:
# 16
np.savetxt('random_data.csv', random_array, delimiter=',')
print("random_data.csv saved successfully.")

random_data.csv saved successfully.


In [96]:
# 17
loaded_array = np.loadtxt('random_data.csv', delimiter=',')

In [97]:
# 18
loaded_array_sum = np.sum(loaded_array)
loaded_array_cumsum = np.cumsum(loaded_array)
loaded_array_mean = np.mean(loaded_array)

In [98]:
loaded_array

array([100.,  70.,   2.,  76.,  69.,   2.,  78.,  20.,  14., 100.])

In [99]:
print('sum', loaded_array_sum)
print('*'*10)
print('cumsum', loaded_array_cumsum)
print('*'*10)
print('mean', loaded_array_mean)

sum 531.0
**********
cumsum [100. 170. 172. 248. 317. 319. 397. 417. 431. 531.]
**********
mean 53.1


In [100]:
identity_matrix_deleted

array([[0., 1., 0.],
       [0., 0., 1.]])

In [101]:
# 19
column_means_identity = np.mean(identity_matrix_deleted, axis=0)
print("column_means_identity: \n",column_means_identity)

column_means_identity: 
 [0.  0.5 0.5]


In [102]:
# 20
results=np.array([loaded_array_sum, loaded_array_mean])
print("results : ", results)
np.savetxt('results.csv', results)
print("results.csv saved successfully.")

results :  [531.   53.1]
results.csv saved successfully.


<hr>

# Exercise 2: Solar Energy Calculation

<p style="text-align:center">
    <img src="https://th.bing.com/th/id/R.b3c79851427a8a55723fe3827b31abec?rik=hhIrP8ict8gxIw&riu=http%3a%2f%2fnews.delaware.gov%2ffiles%2f2012%2f03%2fMotech-Solar-Panel-floating.jpg&ehk=Q3uAu91jOrnoGRCY6%2bd9acDMq6CEzBIKGJLdw9zD5B0%3d&risl=&pid=ImgRaw&r=0" width="500" height="200" alt="Solar Energy"  />
</p>

$$
E = A \times \eta \times I \times t
$$


1. Develop a script that utilizes the `pandas` library to read the contents of the csv file named `"solar_energy_data_by_binatnaData.csv"` into a DataFrame, and assign it the variable name `df`.
2. Display the first and last few rows of the DataFrame using the `head()` and `tail()` functions, and the column names. 
3. Rename the columns by the following names : `A, E, I, T`
4. Determine and print the `count of missing (NaN) values` for each column in the DataFrame.
5. Eliminate the `rows containing NaN values` from the DataFrame.
6. Check for `duplicate rows` in the DataFrame using the `duplicated()` method.
7. Calculate the Energy for each row by applying the formula: `Energy = Solar Panel Area * Solar Panel Efficiency * Solar Irradiance * Time`.
8. Calculate the energy for each row by applying the same `formula`, this time using a `function` that takes 4 `arguments`: A (Area), E (Efficiency), I (Irradiance), T (Time), then the function returns the calculated Energy. 
9. Introduce a new column in the DataFrame, naming it `"Energy"` and populate it with the calculated energy values.
9. Save the modified DataFrame with the additional `Energy` column to a `new csv file`.

In [107]:
import pandas as pd
import numpy as np

In [110]:
# 1
#read the csv file
df = pd.read_csv("data/solar_energy_data_by_binatnaData.csv")

In [67]:
# 2

In [109]:
df.head()

Solar Panel Area   Solar Panel Efficiency    Solar Irradiance   \
0               20.0                      18.5               200.0   
1               15.0                      21.2               180.0   
2               25.0                      16.8               220.0   
3               30.0                      20.1               250.0   
4               18.0                      19.3               190.0   

    Time in Hour   
0             6.0  
1             8.0  
2             4.0  
3             7.0  
4             5.0

In [66]:
df.tail()

Solar Panel Area   Solar Panel Efficiency    Solar Irradiance   \
28               11.0                      21.0               170.0   
29               25.0                      19.7               220.0   
30               37.0                      17.9               240.0   
31               15.0                      20.2               190.0   
32               28.0                      16.7               260.0   

     Time in Hour   
28             8.0  
29             5.0  
30             7.0  
31             4.0  
32            10.0

In [111]:
# list the column names
df.columns

Index([' Solar Panel Area', ' Solar Panel Efficiency ', ' Solar Irradiance ',
       ' Time in Hour '],
      dtype='object')

In [124]:
# 3
# rename columns
df.rename(columns = {' Solar Panel Area': 'A',
                     ' Solar Panel Efficiency ': 'E',
                     ' Solar Irradiance ' : 'I',
                     ' Time in Hour ' : 'T'
                    }, inplace=True)

In [125]:
# verify 
df.head(1)

A     E      I    T
0  20.0  18.5  200.0  6.0

In [126]:
# 4
# count the number of nan values for each column
df.isnull().sum()

A    0
E    0
I    0
T    0
dtype: int64

In [127]:
print('The total number of missing values is {}'.format(df.isnull().sum().sum()))

The total number of missing values is 0


In [118]:
# 5
# drop nan values 
df.dropna(axis=0, inplace=True)

In [128]:
# check if nan values are deleted
df.isnull().sum()

A    0
E    0
I    0
T    0
dtype: int64

In [129]:
print('The total number of missing values is {}'.format(df.isnull().sum().sum()))

The total number of missing values is 0


In [130]:
# 6
# count the number of duplicated rows
df.duplicated().sum()

0

In [131]:
# drop duplicated rows (in case)
df.drop_duplicates(inplace=True)

In [133]:
# 7
# calculate energy without using function
df['Energy'] = df['A'] * df['E'] * df['I'] * df['T']

In [134]:
# check
df.head()

A     E      I    T     Energy
0  20.0  18.5  200.0  6.0   444000.0
1  15.0  21.2  180.0  8.0   457920.0
2  25.0  16.8  220.0  4.0   369600.0
3  30.0  20.1  250.0  7.0  1055250.0
4  18.0  19.3  190.0  5.0   330030.0

In [135]:
# 8
# define the calculate energy function
def calculate_energy(A, E, I, T):
    return A*E*I*T

# init a list to store energies 
energy_list = []
for index, row in df.iterrows(): # iterrows to iterate the df row by row
    temp_A = row["A"]
    temp_E = row["E"]
    temp_I = row["I"]
    temp_T = row["T"]
    temp_E = calculate_energy(temp_A, temp_E, temp_I, temp_T)
    energy_list.append(temp_E)

# 9
# create new column 
df["Energy_2"] = energy_list

In [136]:
# display the resulted df
df.head()

A     E      I    T     Energy   Energy_2
0  20.0  18.5  200.0  6.0   444000.0   444000.0
1  15.0  21.2  180.0  8.0   457920.0   457920.0
2  25.0  16.8  220.0  4.0   369600.0   369600.0
3  30.0  20.1  250.0  7.0  1055250.0  1055250.0
4  18.0  19.3  190.0  5.0   330030.0   330030.0

In [140]:
# second method to calculate the energy, optimized
def calculate_energy_by_row(row):
    return row['A'] * row['E'] * row['I'] * row['T']

df["Energy_3"] = df.apply(calculate_energy_by_row, axis=1)

In [141]:
df.head()

A     E      I    T     Energy   Energy_2   Energy_3
0  20.0  18.5  200.0  6.0   444000.0   444000.0   444000.0
1  15.0  21.2  180.0  8.0   457920.0   457920.0   457920.0
2  25.0  16.8  220.0  4.0   369600.0   369600.0   369600.0
3  30.0  20.1  250.0  7.0  1055250.0  1055250.0  1055250.0
4  18.0  19.3  190.0  5.0   330030.0   330030.0   330030.0

In [142]:
# 10
df.to_csv("newData.csv", index=False)

---
### Python Labs (C) 2023 [BinatnaData](https://www.linkedin.com/company/100193879/) Corporation

<p style="text-align:center">
    <a href="https://www.linkedin.com/company/100193879/" target="_blank">
    <img src="https://raw.githubusercontent.com/binatnadata/event2-python-ERME_CLUB/main/assets/logo.png" width="100" height="100" alt="Binatna Data Logo"  />
    </a>